name: taskflow

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/var/www
    environment:
      - PHP_IDE_CONFIG=serverName=taskflow
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: taskflow
      MYSQL_USER: taskflow
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    volumes:
      - taskflow_db_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    ports:
      - "6381:6379"

  adminer:
    image: adminer:latest
    ports:
      - "8082:8080"
    depends_on:
      - db

volumes:
  taskflow_db_data:
